### ISSUE TITLE
Crash when using the mod

### ISSUE THREAD

**Issue by EchoEllet** [lack/way2wayfabric#8]
I'm unable to use this mod

```console

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'way2wayfabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: net/blay09/mods/waystones/api/KnownWaystonesEvent
	at com.jimramsay.way2wayfabric.BlayWaystones.register(BlayWaystones.kt:22)
	at com.jimramsay.way2wayfabric.Way2WayFabric.onInitialize(Way2WayFabric.kt:228)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.blay09.mods.waystones.api.KnownWaystonesEvent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 12 more

```

with the latest version of minecraft 1.20.4, fabric, and waystones

**Comment by byung806** [comment]
Same here - v0.0.6 says it supports 1.20.4 but it seems to be using the old Waypoints API events.

I looked at the source (way2wayfabric-0.0.6.zip) and it doesn't seem to be the 1.20.4 branch version (it still uses KnownWaystonesEvent instead of WaystonesListReceivedEvent in BlayWaystones.kt).

Would it be possible to build the 1.20.4 branch as a jar and upload that as a release? The issue should be fixed by doing that.

**Comment by ellet0** [comment]
> Same here - v0.0.6 says it supports 1.20.4 but it seems to be using the old Waypoints API events.
> 
> I looked at the source (way2wayfabric-0.0.6.zip) and it doesn't seem to be the 1.20.4 branch version (it still uses KnownWaystonesEvent instead of WaystonesListReceivedEvent in BlayWaystones.kt).
> 
> Would it be possible to build the 1.20.4 branch as a jar and upload that as a release? The issue should be fixed by doing that.

You might want to send a PR to fix that when you have the time

I might do that if no one did

**Comment by byung806** [comment]
I generated the 1.20.4 branch and published as a release in my forked repo.
The game now is able to launch but it crashes for me when I try to place a waystone in the world

![unknown](https://github.com/lack/way2wayfabric/assets/87292945/01ad6cf1-4b58-4bf1-93a8-4909c34deaa8)

I checked in the Waystones repo and the API does indeed have getPos() as a function (https://github.com/TwelveIterationMods/Waystones/blob/1.20.x/shared/src/main/java/net/blay09/mods/waystones/api/Waystone.java) - not sure how to resolve this crash. Any ideas?

**Comment by ellet0** [comment]
> I generated the 1.20.4 branch and published as a release in my forked repo.
> The game now is able to launch but it crashes for me when I try to place a waystone in the world
> 
> ![unknown](https://github.com/lack/way2wayfabric/assets/87292945/01ad6cf1-4b58-4bf1-93a8-4909c34deaa8)
> 
> I checked in the Waystones repo and the API does indeed have getPos() as a function (https://github.com/TwelveIterationMods/Waystones/blob/1.20.x/shared/src/main/java/net/blay09/mods/waystones/api/Waystone.java) - not sure how to resolve this crash. Any ideas?

Unfortunately, I'm not familiar with minecraft api nor fabric

Yes, I can read any code written in java, but I do not necessarily understand it

Believe me I know less than you

You might want to create an issue in this repo for that exception

**Comment by lack** [comment]
Thanks for the reminder...  I was part-way through the new implementation, but then hit some issues; I'll try to revive that soon!

**Comment by RosivDamotil** [comment]
Same here.
Worked find on 1.19.4 but now crashes every startup.

**Comment by fokichev** [comment]
hullo, just to add that I have the same issue/version/error as original comment, in case this got lost and is an easy fix. No worries if not - already appreciate the open source efforts. Thanks to the previous commenters for troubleshooting too, wish I knew more about Java to make a PR myself.
